import { Property } from './types';

const PROPERTY_IMAGES = [
  'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
  'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
  'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
  'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
  'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80',
  'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
  'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
  'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
  'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
  'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80',
  'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80',
  'https://images.unsplash.com/photo-1628744448839-99849e5b3e29?w=800&q=80',
];

export const sampleProperties: Property[] = [
  {
    id: '1',
    title: 'Appartement Moderne Kipé',
    type: 'Appartement',
    commune: 'Ratoma',
    quartier: 'Kipé',
    surfaceM2: 120,
    totalRooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    floor: 2,
    furnished: 'Meublé',
    condition: 'Neuf',
    waterSupply: 'SEEG fiable',
    electricityType: 'EDG fiable',
    hasGenerator: true,
    generatorIncluded: true,
    hasAC: true,
    acCount: 3,
    hasParking: true,
    hasSecurity: true,
    hasInternet: true,
    hasHotWater: true,
    accessibleInRain: true,
    priceGNF: 15000000,
    priceUSD: 1500,
    preferredCurrency: 'GNF',
    chargesIncluded: false,
    depositMonths: 2,
    advanceMonths: 3,
    negotiable: true,
    petsAllowed: false,
    smokingAllowed: false,
    maxOccupants: 6,
    availableFrom: '2026-03-01',
    minDurationMonths: 12,
    isVerified: true,
    images: [PROPERTY_IMAGES[0], PROPERTY_IMAGES[1], PROPERTY_IMAGES[2]],
    description: 'Magnifique appartement moderne situé dans le quartier prisé de Kipé. Entièrement meublé avec des finitions haut de gamme. Groupe électrogène inclus dans le loyer, eau et électricité fiables. Parking sécurisé et gardiennage 24h/24.',
    viewCount: 234,
    leadCount: 12,
    ownerId: 'owner1',
    ownerName: 'Mamadou Diallo',
    createdAt: '2026-01-15',
  },
  {
    id: '2',
    title: 'Villa avec Jardin Nongo',
    type: 'Villa',
    commune: 'Ratoma',
    quartier: 'Nongo',
    surfaceM2: 250,
    totalRooms: 8,
    bedrooms: 4,
    bathrooms: 3,
    furnished: 'Semi-meublé',
    condition: 'Bon état',
    waterSupply: 'SEEG intermittente',
    electricityType: 'EDG intermittente',
    hasGenerator: true,
    generatorIncluded: false,
    hasAC: true,
    acCount: 2,
    hasParking: true,
    hasSecurity: true,
    hasInternet: false,
    hasHotWater: true,
    accessibleInRain: false,
    priceGNF: 25000000,
    priceUSD: 2500,
    preferredCurrency: 'GNF',
    chargesIncluded: false,
    depositMonths: 3,
    advanceMonths: 6,
    negotiable: true,
    petsAllowed: true,
    smokingAllowed: false,
    maxOccupants: 10,
    availableFrom: '2026-02-20',
    minDurationMonths: 24,
    isVerified: true,
    images: [PROPERTY_IMAGES[3], PROPERTY_IMAGES[4], PROPERTY_IMAGES[5]],
    description: 'Spacieuse villa avec grand jardin dans le quartier calme de Nongo. Idéale pour famille nombreuse ou expatriés. Groupe électrogène disponible. Quartier résidentiel avec bon voisinage.',
    viewCount: 189,
    leadCount: 8,
    ownerId: 'owner2',
    ownerName: 'Aissatou Barry',
    createdAt: '2026-01-20',
  },
  {
    id: '3',
    title: 'Studio Centre-Ville Kaloum',
    type: 'Studio',
    commune: 'Kaloum',
    quartier: 'Boulbinet',
    surfaceM2: 35,
    totalRooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    furnished: 'Meublé',
    condition: 'Bon état',
    waterSupply: 'SEEG fiable',
    electricityType: 'EDG fiable',
    hasGenerator: false,
    generatorIncluded: false,
    hasAC: true,
    acCount: 1,
    hasParking: false,
    hasSecurity: false,
    hasInternet: true,
    hasHotWater: false,
    accessibleInRain: true,
    priceGNF: 5000000,
    priceUSD: 500,
    preferredCurrency: 'GNF',
    chargesIncluded: true,
    depositMonths: 1,
    advanceMonths: 2,
    negotiable: false,
    petsAllowed: false,
    smokingAllowed: false,
    maxOccupants: 2,
    availableFrom: '2026-02-01',
    minDurationMonths: 6,
    isVerified: false,
    images: [PROPERTY_IMAGES[6], PROPERTY_IMAGES[7]],
    description: 'Studio fonctionnel en plein centre de Kaloum. Proche des commerces et transports. Charges incluses dans le loyer. Idéal pour jeune professionnel ou étudiant.',
    viewCount: 456,
    leadCount: 24,
    ownerId: 'owner3',
    ownerName: 'Ibrahim Camara',
    createdAt: '2026-02-01',
  },
  {
    id: '4',
    title: 'Duplex Standing Matam',
    type: 'Duplex',
    commune: 'Matam',
    quartier: 'Lansanayah',
    surfaceM2: 180,
    totalRooms: 7,
    bedrooms: 4,
    bathrooms: 3,
    floor: 0,
    furnished: 'Vide',
    condition: 'Neuf',
    waterSupply: 'SEEG fiable',
    electricityType: 'EDG intermittente',
    hasGenerator: true,
    generatorIncluded: true,
    hasAC: false,
    hasParking: true,
    hasSecurity: true,
    hasInternet: true,
    hasHotWater: true,
    accessibleInRain: true,
    priceGNF: 20000000,
    priceUSD: 2000,
    preferredCurrency: 'GNF',
    chargesIncluded: false,
    depositMonths: 2,
    advanceMonths: 4,
    negotiable: true,
    petsAllowed: false,
    smokingAllowed: false,
    maxOccupants: 8,
    availableFrom: '2026-03-15',
    minDurationMonths: 12,
    isVerified: true,
    images: [PROPERTY_IMAGES[8], PROPERTY_IMAGES[9], PROPERTY_IMAGES[10]],
    description: 'Duplex neuf haut standing avec finitions de qualité. Groupe électrogène inclus. Quartier résidentiel calme avec accès facile. Sécurité 24h/24.',
    viewCount: 312,
    leadCount: 15,
    ownerId: 'owner4',
    ownerName: 'Ousmane Sylla',
    createdAt: '2026-01-28',
  },
  {
    id: '5',
    title: 'Chambre Meublée Dixinn',
    type: 'Chambre',
    commune: 'Dixinn',
    quartier: 'Belle Vue',
    surfaceM2: 20,
    totalRooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    furnished: 'Meublé',
    condition: 'Bon état',
    waterSupply: 'SEEG intermittente',
    electricityType: 'EDG intermittente',
    hasGenerator: false,
    generatorIncluded: false,
    hasAC: false,
    hasParking: false,
    hasSecurity: false,
    hasInternet: false,
    hasHotWater: false,
    accessibleInRain: true,
    priceGNF: 2000000,
    priceUSD: 200,
    preferredCurrency: 'GNF',
    chargesIncluded: false,
    depositMonths: 1,
    advanceMonths: 1,
    negotiable: true,
    petsAllowed: false,
    smokingAllowed: false,
    maxOccupants: 2,
    availableFrom: '2026-02-10',
    minDurationMonths: 3,
    isVerified: false,
    images: [PROPERTY_IMAGES[11], PROPERTY_IMAGES[6]],
    description: 'Chambre meublée dans une colocation propre et calme à Dixinn Belle Vue. Accès à la cuisine et à la salle de bain partagées. Vue panoramique.',
    viewCount: 78,
    leadCount: 5,
    ownerId: 'owner5',
    ownerName: 'Fatoumata Bah',
    createdAt: '2026-02-05',
  },
  {
    id: '6',
    title: 'Appartement Familial Matoto',
    type: 'Appartement',
    commune: 'Matoto',
    quartier: 'Cosa',
    surfaceM2: 100,
    totalRooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    floor: 1,
    furnished: 'Vide',
    condition: 'Bon état',
    waterSupply: 'Puits',
    electricityType: 'EDG intermittente',
    hasGenerator: false,
    generatorIncluded: false,
    hasAC: false,
    hasParking: true,
    hasSecurity: false,
    hasInternet: false,
    hasHotWater: false,
    accessibleInRain: false,
    priceGNF: 8000000,
    priceUSD: 800,
    preferredCurrency: 'GNF',
    chargesIncluded: false,
    depositMonths: 2,
    advanceMonths: 3,
    negotiable: true,
    petsAllowed: true,
    smokingAllowed: true,
    availableFrom: '2026-02-15',
    minDurationMonths: 12,
    isVerified: false,
    images: [PROPERTY_IMAGES[1], PROPERTY_IMAGES[4], PROPERTY_IMAGES[9]],
    description: 'Grand appartement familial à Matoto Cosa. Proche des écoles et marchés. Idéal pour famille avec enfants. Parking disponible.',
    viewCount: 145,
    leadCount: 9,
    ownerId: 'owner6',
    ownerName: 'Alpha Bah',
    createdAt: '2026-02-08',
  },
  {
    id: '7',
    title: 'Villa Prestige Kipé T4',
    type: 'Villa',
    commune: 'Ratoma',
    quartier: 'Kipé',
    surfaceM2: 300,
    totalRooms: 10,
    bedrooms: 5,
    bathrooms: 4,
    furnished: 'Meublé',
    condition: 'Neuf',
    waterSupply: 'SEEG fiable',
    electricityType: 'EDG fiable',
    hasGenerator: true,
    generatorIncluded: true,
    hasAC: true,
    acCount: 5,
    hasParking: true,
    hasSecurity: true,
    hasInternet: true,
    hasHotWater: true,
    accessibleInRain: true,
    priceGNF: 45000000,
    priceUSD: 4500,
    preferredCurrency: 'USD',
    chargesIncluded: true,
    depositMonths: 3,
    advanceMonths: 6,
    negotiable: false,
    petsAllowed: true,
    smokingAllowed: false,
    maxOccupants: 12,
    availableFrom: '2026-04-01',
    minDurationMonths: 24,
    isVerified: true,
    images: [PROPERTY_IMAGES[5], PROPERTY_IMAGES[0], PROPERTY_IMAGES[2], PROPERTY_IMAGES[8]],
    description: 'Villa de prestige entièrement meublée à Kipé. Piscine privée, jardin paysager, groupe électrogène de secours. Service de gardiennage premium. Toutes charges incluses.',
    viewCount: 567,
    leadCount: 3,
    ownerId: 'owner7',
    ownerName: 'Sékou Touré',
    createdAt: '2026-01-10',
  },
  {
    id: '8',
    title: 'Maison Traditionnelle Matam',
    type: 'Maison',
    commune: 'Matam',
    quartier: 'Madina',
    surfaceM2: 150,
    totalRooms: 6,
    bedrooms: 3,
    bathrooms: 2,
    furnished: 'Vide',
    condition: 'À rénover',
    waterSupply: 'Puits',
    electricityType: 'EDG intermittente',
    hasGenerator: false,
    generatorIncluded: false,
    hasAC: false,
    hasParking: false,
    hasSecurity: false,
    hasInternet: false,
    hasHotWater: false,
    accessibleInRain: false,
    priceGNF: 4000000,
    priceUSD: 400,
    preferredCurrency: 'GNF',
    chargesIncluded: false,
    depositMonths: 1,
    advanceMonths: 2,
    negotiable: true,
    petsAllowed: true,
    smokingAllowed: true,
    availableFrom: '2026-02-01',
    minDurationMonths: 6,
    isVerified: false,
    images: [PROPERTY_IMAGES[10], PROPERTY_IMAGES[3]],
    description: 'Maison traditionnelle dans le quartier animé de Madina. À rénover mais offrant un grand potentiel. Proche du marché central de Madina.',
    viewCount: 89,
    leadCount: 4,
    ownerId: 'owner8',
    ownerName: 'Mariama Sow',
    createdAt: '2026-02-12',
  },
];
